### ISSUE TITLE
jq required on local machine

### ISSUE THREAD

**Issue by ekandreas** [stefanprodan/k8s-scw-arm#47]
`./scripts/kubeadm-token.sh` requires the commandline json processor `jq` installed.
For macOS: `brew install jq`
Perhaps this should be added to the readme?

(thanks to a really nice terraform lib!)

**Comment by stephenmoloney** [comment]
A note is in there but perhaps the installation directions could be more explicit

https://github.com/stefanprodan/k8s-scw-baremetal/blame/master/README.md#L37

**Comment by ekandreas** [comment]
ahhh, great! It was so small that I missed it.
Right now I have provisioned around 20 machines with your scripts. And destroyed them :-)
Works really well.
